services:
  userservice:
    build:
      context: .
      dockerfile: Dockerfile
    image: local/userservice:latest
    container_name: userservice
    command: ./services/userService/main.js
    environment:
      - PORT=4001
      - NODE_ENV=development
    ports:
      - "4001:4001"
  messageservice:
    build:
      context: .
      dockerfile: Dockerfile
    image: local/userservice:latest
    container_name: messageservice
    command: ./services/messageService/main.js
    environment:
      - PORT=4002
      - NODE_ENV=development
    ports:
      - "4002:4002"
  authservice:
    build:
      context: .
      dockerfile: Dockerfile
    image: local/authservice:latest
    container_name: authservice
    command: ./services/authService/main.js
    environment:
      - PORT=4003
      - NODE_ENV=development
    ports:
      - "4003:4003"
